/**
 * downloadReport.js
 * ---------------------------------------------------------------------------
 * Client-side, prototype-only report export. Builds a plain-text summary
 * from the same mock data shown in the report preview and triggers a
 * browser download. No server involved — this is purely for demoing the
 * "Download Report" action until a real report-generation API exists.
 * ---------------------------------------------------------------------------
 */

export function buildReportText(report, watershed, data) {
  const { summary, priorityAreas, insights } = data;

  const lines = [
    `GEOVISION — ${report.name}`,
    `Watershed: ${watershed.name}`,
    `Date: ${report.date}`,
    `Status: ${report.status}`,
    '',
    '--- Summary ---',
    `Watershed Health Score: ${summary.healthScore.value}/${summary.healthScore.max}`,
    `Vegetation Change: ${summary.vegetationChange.value > 0 ? '+' : ''}${summary.vegetationChange.value}${summary.vegetationChange.unit}`,
    `Water Availability: ${summary.waterAvailability.value > 0 ? '+' : ''}${summary.waterAvailability.value}${summary.waterAvailability.unit}`,
    `Interventions Monitored: ${summary.interventionsMonitored.value}`,
    '',
    '--- Priority Areas ---',
    ...priorityAreas.map((a) => `- ${a.location}: ${a.issue} (Severity: ${a.severity}, Status: ${a.status})`),
    '',
    '--- Key Insights ---',
    ...insights.map((i) => `- ${i.text}`),
    '',
    'Generated by GEOVISION — prototype export, mock data.',
  ];

  return lines.join('\n');
}

export function downloadTextFile(filename, content) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
